name: Build and Release FACEIT Analyze

on:
  push:
    tags:
      - 'v*'  # Запускается при создании тега версии (например, v1.0.0)
  workflow_dispatch:  # Позволяет запустить вручную

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kivy[base] requests python-dotenv pyinstaller Pillow
        
    - name: Create .env file
      run: |
        echo "FACEIT_API_KEY=${{ secrets.FACEIT_API_KEY }}" > .env
        
    - name: Build executable
      run: |
        pyinstaller faceit_tracker.spec
        
    - name: Verify build
      run: |
        if (Test-Path "dist/FACEIT Analyze.exe") {
          Write-Host "Build successful - executable found"
          Get-ChildItem "dist/FACEIT Analyze.exe" | Format-List
        } else {
          Write-Error "Build failed - executable not found"
          exit 1
        }
        
    - name: Create release archive
      run: |
        Compress-Archive -Path "dist/FACEIT Analyze.exe" -DestinationPath "FACEIT-Analyze-Windows.zip"
        
    - name: Get version from tag
      id: version
      run: |
        if ($env:GITHUB_REF -match "refs/tags/(.*)") {
          $version = $matches[1]
        } else {
          $version = "dev-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
        }
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: FACEIT Analyze ${{ steps.version.outputs.VERSION }}
        body: |
          ## FACEIT Analyze ${{ steps.version.outputs.VERSION }}
          
          🎮 **Анализатор статистики FACEIT для CS:2**
          
          ### 📋 Что нового:
          - Автоматическая сборка через GitHub Actions
          - Улучшенная стабильность
          - Поддержка CS:2 статистики
          
          ### 📦 Установка:
          1. Скачайте `FACEIT-Analyze-Windows.zip`
          2. Распакуйте архив
          3. Запустите `FACEIT Analyze.exe`
          
          ### 🔧 Системные требования:
          - Windows 10/11
          - Интернет соединение
          
          ### 📖 Использование:
          - Введите никнейм игрока или ссылку на профиль FACEIT
          - Нажмите кнопку "SCAN"
          - Просмотрите детальную статистику
          
          ---
          🔗 [Исходный код](https://github.com/${{ github.repository }})
        files: |
          FACEIT-Analyze-Windows.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}